// Code generated by sqlc. DO NOT EDIT.
// source: user.sql

package db

import (
	"context"
)

const changeBlockedStatus = `-- name: ChangeBlockedStatus :exec
UPDATE users
SET isBlocked = $2
WHERE id = $1
`

type ChangeBlockedStatusParams struct {
	ID        int64 `json:"id"`
	Isblocked bool  `json:"isblocked"`
}

func (q *Queries) ChangeBlockedStatus(ctx context.Context, arg ChangeBlockedStatusParams) error {
	_, err := q.db.ExecContext(ctx, changeBlockedStatus, arg.ID, arg.Isblocked)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  hashed_password,
  email,
  avatar
) VALUES (
  $1, $2, $3, $4
) RETURNING id, username, hashed_password, email, avatar, password_changed_at, created_at, isblocked
`

type CreateUserParams struct {
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
	Email          string `json:"email"`
	Avatar         string `json:"avatar"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.HashedPassword,
		arg.Email,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.Email,
		&i.Avatar,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.Isblocked,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, hashed_password, email, avatar, password_changed_at, created_at, isblocked FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.Email,
		&i.Avatar,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.Isblocked,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, hashed_password, email, avatar, password_changed_at, created_at, isblocked FROM users
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.Email,
			&i.Avatar,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.Isblocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET hashed_password = $2
WHERE id = $1
RETURNING id, username, hashed_password, email, avatar, password_changed_at, created_at, isblocked
`

type UpdateUserParams struct {
	ID             int64  `json:"id"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.Email,
		&i.Avatar,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.Isblocked,
	)
	return i, err
}
